exports.SysComponent = require('./sys.js')
exports.NovaExchangeComponent = require('./novaexchange.js')
exports.SuprnovaComponent = require('./suprnova.js')
exports.BitXComponent = require('./bitx.js')
exports.BittrexComponent = require('./bittrex.js')
exports.PoloniexComponent = require('./poloniex.js')
exports.CoinMarketCapComponent = require('./coinmarketcap.js')
exports.shared = require('./shared.js')
